macro(set_root_namespace arg1)
  set_property(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} PROPERTY YTLIB_CURRENT_NAMESPACE ${arg1})
endmacro()

macro(set_namespace)
  string(REGEX REPLACE ".*/\(.*\)" "\\1" YTLIB_CUR_DIR ${CMAKE_CURRENT_SOURCE_DIR})
  get_directory_property(YTLIB_CUR_DIRECTORY_PARENT PARENT_DIRECTORY)
  get_property(
    YTLIB_SUPERIOR_NAMESPACE
    DIRECTORY ${YTLIB_CUR_DIRECTORY_PARENT}
    PROPERTY YTLIB_CURRENT_NAMESPACE)
  set_property(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} PROPERTY YTLIB_CURRENT_NAMESPACE ${YTLIB_SUPERIOR_NAMESPACE}::${YTLIB_CUR_DIR})
endmacro()

macro(get_namespace arg1)
  get_directory_property(YTLIB_CUR_DIRECTORY_PARENT PARENT_DIRECTORY)
  get_property(
    ${arg1}
    DIRECTORY ${YTLIB_CUR_DIRECTORY_PARENT}
    PROPERTY YTLIB_CURRENT_NAMESPACE)
  if(${arg1} STREQUAL "")
    message(FATAL_ERROR "Can not get namespace for ${CMAKE_CURRENT_SOURCE_DIR}")
  endif()
endmacro()
